name: CMAND Actions Demo
run-name: ${{ github.actor }} publishing ğŸš€
on: [push]
jobs:
  Course-Update:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: read
      actions: read
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Setup pages
        uses: actions/configure-pages@v5
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: mkdir -p output    
      - name: Running python job2
        run: |
          python3 hello.py > output/hello.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello.txt
          path: output
          
      - name: Upload static files
        id: deployment
        uses: actions/deploy-pages@v4
        
      - run: echo "ğŸ This job's status is ${{ job.status }}."
