name: CMAND Actions Demo
run-name: ${{ github.actor }} publishing ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: mkdir -p output    
      - name: Running python job2
        run: |
          python3 hello.py > output/hello.txt
      - name: Update artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: hello.txt
          path: output
          
      - name: Upload static files
        id: deployment
        uses: actions/deploy-pages@v4
        
      - run: echo "ğŸ This job's status is ${{ job.status }}."
